name: 'KFJ Hello World'
description: 'Testing out GitHub NodeJS Actions'
author: 'Kristian Jones'
inputs:
  input-1:
    description: 'Testing Input #1'
    default: 'hWorld'
runs:
  using: 'docker'
  image: 'Dockerfile'